name: Sync LeetCode
on:
  workflow_dispatch:     # Allows you to trigger this manually
  schedule:
    - cron: '0 8 * * *'  # Runs automatically every day at 8:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Solutions
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'solutions'
